# Use a local package cache, instead of the global shared cache of Yarn
enableGlobalCache: false

# Do not report usage
enableTelemetry: false

# Allow the injection of global environment variables
injectEnvironmentFiles:
  - .env?
  - .env.local?
  - .env.yarn?

# Enforce strict dependency resolution
pnpMode: strict

# Automatically add @types/* when applicable
tsEnableAutoTypes: true

# Keep a local copy of yarn so it's available on the build environment
yarnPath: .yarn/releases/yarn-4.9.0.cjs

# Update dependencies of packages that don't meet the strict dependency 
# resolution requirements.
packageExtensions:
  "@graphql-codegen/cli@^5.0":
    dependencies:
      graphql-sock: "*"
  "@graphql-codegen/plugin-helpers@*":
    dependencies:
      "@graphql-tools/apollo-engine-loader": "*"
  "@inquirer/core@^10.0.0":
    dependencies:
      "@types/node": "*"
  "@rushstack/eslint-patch@*":
    peerDependencies:
      "@eslint/eslintrc": "*"
  "@types/react-dom@*":
    dependencies:
      react: "*"
  "@types/react-transition-group@4.4.10":
    dependencies:
      prop-types: "*"
      scheduler: "*"
  "@types/react@*":
    dependencies:
      prop-types: "*"
      scheduler: "*"
  "@typescript-eslint/type-utils@8.6.0":
    dependencies:
      eslint: "*"
  "@typescript-eslint/utils@8.6.0":
    dependencies:
      typescript: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  eslint-config-next@*:
    peerDependencies:
      "@eslint/eslintrc": "*"
      next: "*"
      react: "*"
      react-dom: "*"
  next@*:
    dependencies:
      sharp: "*"
  node-fetch@*:
    dependencies:
      encoding: "*"
